<div id="wall">
    <?php foreach ($this->filledBottles as $filledBottle): ?>
        <div class="filled-bottle on-table"><img title="<?php print $this->escape('этикетка: ' . $filledBottle->name . ' | напиток: ' . $filledBottle->beverage->name) ?>" src="/img/<?php print $this->escape($filledBottle->bottle->img) ?>"</div>
    <?php endforeach; ?>
    <div id="songline"></div>
</div>
<a href="#" id="sing-song">sing!</a>&nbsp;&nbsp;&nbsp;<a href="#" id="stop-song">stop!</a>&nbsp;&nbsp;&nbsp;<a href="/" id="new-song">once more!</a>