<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>99 Bottles</title>
<?php
    print $this->headLink()->appendStylesheet('/css/style.css');
    $this->headScript()->appendFile('/js/jquery.js', 'text/javascript');
    $this->headScript()->appendFile('/js/chain.js', 'text/javascript');
    $this->headScript()->appendFile('/js/script.js', 'text/javascript');
    print $this->headScript();
?>
</head>
<body>
<div id="header">
	<h1>99 Bottles</h1>
    <div id="search-form-block"><?php print $this->searchform; ?></div>
	<ul id="header-navigation">
		<li><a href="<?php echo $this->url(array('controller'=>'index'), 'default', true) ?>">Main (sing)</a></li>
		<li><a href="<?php echo $this->url(array('controller'=>'filledbottles'), 'default', true) ?>">Filled Bottles</a></li>
		<li><a href="<?php echo $this->url(array('controller'=>'bottles'), 'default', true) ?>">Bottles</a></li>
		<li><a href="<?php echo $this->url(array('controller'=>'beverages'), 'default', true) ?>">Beverages</a></li>
	</ul>
</div>

<?php echo $this->layout()->content ?>
<div id="footer">especially for bankir.ru</div>
</body>
</html>
<!-- application/layouts/scripts/layout.phtml -->